<!DOCTYPE html>
<html>
<head>
<meta http-equiv='Content-Type' content='text/html;charset=utf-8'>
<title>Linear Neural Network test page</title>
<script type='text/javascript' src='LinearNeuralNetwork.class.js'></script>
<script type='text/javascript'>
var n = new LinearNeuralNetwork(60, 8, 2, 3, 1, 1);
var c = false;
var y = 0;
function loop() {
    var tmp;
    if(!c) c = document.getElementById('canvas').getContext('2d');
    for(var x = 0; x < 500; x++) {
        tmp = n.think([x / 500, y / 400]);
        c.fillStyle = "rgb(" + Math.floor(tmp[0] * 127 + 127) + "," + Math.floor(tmp[1] * 127 + 127) + "," + Math.floor(tmp[2] * 127 + 127) + ")";
        c.fillRect(x, y, 1, 1);
    }
    y++;
    if(y > 399) {
        n.mutate(1); // Mutate one neuron
        y -= 400;
    }
    setTimeout(loop, 10);
}
function reset_nn() {
    var size = parseInt(document.getElementById('size').value);
    if(isNaN(size)) return;
    if(size < 5) size = 5;
    if(size > 9999) size = 9999;
    var complexity = parseInt(document.getElementById('complexity').value);
    if(isNaN(complexity)) return;
    if(complexity < 1) complexity = 1;
    if(complexity > size) complexity = size;
    n = new LinearNeuralNetwork(size, complexity, 2, 3, 1, 1);
}
</script>
</head>
<body onload='loop()'>
<canvas width='500' height='400' id='canvas'></canvas>
<table><tr>
    <td colspan='2'>Neural network settings (High numbers may lock your browser for some time)</td>
</tr><tr>
    <td>Size (min 5, default 60):</td>
    <td><input type='text' value='60' id='size'></td>
</tr><tr>
    <td>Complexity (min 1, default 8):</td>
    <td><input type='text' value='8' id='complexity'></td>
</tr><tr>
    <td></td>
    <td><input type='button' value='Update' onclick='reset_nn()'></td>
</tr></table>
</body>
</html>
